# Generated by Django 4.2.7 on 2024-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_technician_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='open_status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unassigned', 'unassigned'), ('assigned', 'assigned'), ('resolution', 'resolution')], default='unassigned', max_length=50),
        ),
    ]
