# Generated by Django 4.2.7 on 2024-01-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_remove_ticket_open_status_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messsage',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='messages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tasks.messsage'),
            preserve_default=False,
        ),
    ]
