# Generated by Django 4.2.7 on 2024-01-13 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_remove_messsage_ticket_ticket_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='messages',
            new_name='message',
        ),
    ]
